In [1]:
%matplotlib inline

In [4]:
from __future__ import print_function
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.1635e+30,  3.0774e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  4.4842e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22,  0.0000e+00]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0233, 0.6443, 0.7537],
        [0.8475, 0.8661, 0.9887],
        [0.9136, 0.3410, 0.3878],
        [0.0499, 0.5434, 0.0494],
        [0.7021, 0.6462, 0.7768]])


In [7]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4713,  1.8260, -1.6867],
        [ 0.2357,  0.4131, -0.1001],
        [ 0.9036, -0.9993, -0.2873],
        [ 1.4801, -0.9741,  0.4115],
        [-0.5060, -0.6695, -0.0474]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5,3)
print(x + y)

tensor([[ 2.4290,  2.1119, -0.9091],
        [ 0.7183,  0.4277,  0.0228],
        [ 1.4061, -0.5677,  0.4522],
        [ 2.1556, -0.4245,  0.4761],
        [-0.3166, -0.1710,  0.9147]])


In [12]:
print(torch.add(x, y))

tensor([[ 2.4290,  2.1119, -0.9091],
        [ 0.7183,  0.4277,  0.0228],
        [ 1.4061, -0.5677,  0.4522],
        [ 2.1556, -0.4245,  0.4761],
        [-0.3166, -0.1710,  0.9147]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.4290,  2.1119, -0.9091],
        [ 0.7183,  0.4277,  0.0228],
        [ 1.4061, -0.5677,  0.4522],
        [ 2.1556, -0.4245,  0.4761],
        [-0.3166, -0.1710,  0.9147]])


In [14]:
y.add_(x)
print(y)

tensor([[ 2.4290,  2.1119, -0.9091],
        [ 0.7183,  0.4277,  0.0228],
        [ 1.4061, -0.5677,  0.4522],
        [ 2.1556, -0.4245,  0.4761],
        [-0.3166, -0.1710,  0.9147]])


In [15]:
print(x[:, 1])

tensor([ 1.8260,  0.4131, -0.9993, -0.9741, -0.6695])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.1366])
-1.1366173028945923


In [18]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [21]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.1366], device='cuda:0')
tensor([-0.1366], dtype=torch.float64)
